use rlean_core::{DateTime, Symbol};
use rust_decimal::Decimal;
use std::{cmp::Ordering, collections::HashMap};

/// Simplified portfolio target for execution (avoids depending on rlean-portfolio-construction)
#[derive(Debug, Clone)]
pub struct ExecutionTarget {
    pub symbol: Symbol,
    /// Desired quantity (positive = long, negative = short, 0 = liquidate)
    pub quantity: Decimal,
    pub tag: String,
}

/// Borrowed execution target for engine hot paths.
#[derive(Debug, Clone, Copy)]
pub struct ExecutionTargetRef<'a> {
    pub symbol: &'a Symbol,
    pub quantity: Decimal,
    pub tag: &'a str,
}

/// An order request generated by execution
#[derive(Debug, Clone)]
pub struct OrderRequest {
    pub order_id: Option<i64>,
    pub symbol: Symbol,
    pub quantity: Decimal,
    pub order_type: ExecutionOrderType,
    pub limit_price: Option<Decimal>,
    pub post_only: bool,
    pub cancel_open_orders: bool,
    pub tag: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionOrderType {
    Market,
    Limit,
    MarketOnOpen,
    MarketOnClose,
    Cancel,
    Update,
}

#[derive(Debug, Clone)]
pub struct ExecutionOpenOrder {
    pub id: i64,
    pub symbol: Symbol,
    pub quantity: Decimal,
    pub filled_quantity: Decimal,
    pub remaining_quantity: Decimal,
    pub order_type: ExecutionOrderType,
    pub limit_price: Option<Decimal>,
    pub post_only: bool,
    pub tag: String,
    pub created_time: DateTime,
    pub last_update_time: Option<DateTime>,
}

/// Current security data needed by execution models
#[derive(Debug, Clone)]
pub struct SecurityData {
    pub symbol: Symbol,
    pub price: Decimal,
    pub bid: Option<Decimal>,
    pub ask: Option<Decimal>,
    /// Current trade volume used by Lean's percent-volume order sizing.
    pub volume: Option<Decimal>,
    /// Average trade price for the current VWAP input, if trade data is present.
    pub vwap_price: Option<Decimal>,
    pub average_volume: Option<Decimal>,
    pub daily_std_dev: Option<Decimal>,
    pub end_time: Option<DateTime>,
    pub lot_size: Decimal,
    pub minimum_price_variation: Decimal,
    pub current_quantity: Decimal, // currently held
    pub open_order_quantity: Decimal,
}

/// Authoritative algorithm services required by execution models.
///
/// C# LEAN passes the algorithm itself to `IExecutionModel.Execute`, so models
/// resolve the current `Security`, projected holdings, buying-power model, and
/// margin state at execution time. This interface preserves that ownership
/// boundary without making the lower-level execution crate depend on
/// `rlean-algorithm`.
pub trait IExecutionAlgorithm: Send + Sync {
    fn is_warming_up(&self) -> bool;
    fn security(&self, symbol: &Symbol) -> Option<SecurityData>;
    fn security_has_data(&self, symbol: &Symbol) -> bool;
    fn security_is_tradable(&self, symbol: &Symbol) -> bool;
    fn projected_quantity(&self, symbol: &Symbol) -> Decimal;
    fn holdings_quantity(&self, symbol: &Symbol) -> Decimal;
    fn above_minimum_order_margin_portfolio_percentage(
        &self,
        symbol: &Symbol,
        quantity: Decimal,
        minimum_order_margin_portfolio_percentage: Decimal,
    ) -> bool;
}

/// Algorithm-aware execution context.
///
/// C# LEAN passes the full QCAlgorithm instance into IExecutionModel.Execute.
/// rlean keeps execution models in a lower-level crate, so this context is the
/// framework boundary: time, securities, portfolio state, and transaction state
/// are passed together instead of as a reduced security snapshot.
pub struct ExecutionContext<'a> {
    pub time: DateTime,
    pub securities: &'a HashMap<u64, SecurityData>,
    pub open_orders: &'a [ExecutionOpenOrder],
    pub portfolio_value: Decimal,
    pub minimum_order_margin_portfolio_percentage: Decimal,
    algorithm: Option<&'a dyn IExecutionAlgorithm>,
}

/// Sorts targets using the same high-level priority as C# LEAN's
/// `PortfolioTargetCollection.OrderByMarginImpact`: position-reducing orders
/// first, then the largest remaining order value.
pub fn sort_targets_by_margin_impact(
    targets: &mut [(u64, Symbol, Decimal)],
    securities: &HashMap<u64, SecurityData>,
) {
    let open_orders = Vec::new();
    let context = ExecutionContext::new(DateTime::MIN, securities, &open_orders, Decimal::ZERO);
    context.sort_targets_by_margin_impact(targets);
}

#[derive(Debug, Clone, Copy)]
struct MarginImpact {
    is_reducing_position: bool,
    order_value: Decimal,
}

fn margin_impact(target: &(u64, Symbol, Decimal), context: &ExecutionContext<'_>) -> MarginImpact {
    let Some(security) = context.security(&target.1) else {
        return MarginImpact {
            is_reducing_position: false,
            order_value: Decimal::ZERO,
        };
    };

    let target_quantity = adjust_by_lot_size(security.lot_size, target.2);
    let existing_quantity = context.projected_quantity(&target.1, security);
    let unordered_quantity = target_quantity - existing_quantity;
    let is_reducing_position =
        existing_quantity != Decimal::ZERO && target_quantity.abs() < existing_quantity.abs();
    let price = if security.price > Decimal::ZERO {
        security.price
    } else {
        Decimal::ZERO
    };

    MarginImpact {
        is_reducing_position,
        order_value: (unordered_quantity * price).abs(),
    }
}

pub fn adjust_by_lot_size(lot_size: Decimal, quantity: Decimal) -> Decimal {
    if lot_size <= Decimal::ZERO || quantity == Decimal::ZERO {
        return quantity;
    }

    let abs_quantity = quantity.abs();
    let mut remainder = abs_quantity % lot_size;
    let missing_for_lot_size = lot_size - remainder;
    if missing_for_lot_size < lot_size / Decimal::from(1_000_000u64) {
        remainder -= lot_size;
    }

    let sign = if quantity < Decimal::ZERO {
        -Decimal::ONE
    } else {
        Decimal::ONE
    };
    (abs_quantity - remainder) * sign
}

impl<'a> ExecutionContext<'a> {
    pub fn new(
        time: DateTime,
        securities: &'a HashMap<u64, SecurityData>,
        open_orders: &'a [ExecutionOpenOrder],
        portfolio_value: Decimal,
    ) -> Self {
        Self {
            time,
            securities,
            open_orders,
            portfolio_value,
            minimum_order_margin_portfolio_percentage: Decimal::ZERO,
            algorithm: None,
        }
    }

    pub fn with_algorithm(mut self, algorithm: &'a dyn IExecutionAlgorithm) -> Self {
        self.algorithm = Some(algorithm);
        self
    }

    pub fn with_minimum_order_margin_portfolio_percentage(mut self, percentage: Decimal) -> Self {
        self.minimum_order_margin_portfolio_percentage = percentage.max(Decimal::ZERO);
        self
    }

    /// C# LEAN `AboveMinimumOrderMarginPortfolioPercentage` guard used by
    /// ImmediateExecutionModel to avoid tiny rebalance noise.
    pub fn above_minimum_order_margin_portfolio_percentage(
        &self,
        security: &SecurityData,
        quantity: Decimal,
    ) -> bool {
        if self.portfolio_value <= Decimal::ZERO
            || self.minimum_order_margin_portfolio_percentage <= Decimal::ZERO
        {
            return true;
        }
        if let Some(algorithm) = self.algorithm {
            return algorithm.above_minimum_order_margin_portfolio_percentage(
                &security.symbol,
                quantity,
                self.minimum_order_margin_portfolio_percentage,
            );
        }

        // Standalone execution-model contexts used by lower-level models and
        // unit tests have no algorithm-owned buying-power model. Production
        // framework execution always delegates above.
        let abs_final_order_margin = (quantity * security.price).abs();
        let minimum_value = self.portfolio_value * self.minimum_order_margin_portfolio_percentage;
        minimum_value <= abs_final_order_margin
    }

    pub fn is_warming_up(&self) -> bool {
        self.algorithm
            .is_some_and(IExecutionAlgorithm::is_warming_up)
    }

    pub fn has_authoritative_algorithm(&self) -> bool {
        self.algorithm.is_some()
    }

    /// Resolve the current security through the algorithm-owned SecurityManager.
    /// A configured algorithm is authoritative: a miss is never replaced with
    /// snapshot data. Standalone model contexts use their explicit snapshot.
    pub fn authoritative_security(&self, symbol: &Symbol) -> Option<SecurityData> {
        match self.algorithm {
            Some(algorithm) => algorithm.security(symbol),
            None => self.security(symbol).cloned(),
        }
    }

    pub fn security_has_data(&self, security: &SecurityData) -> bool {
        self.algorithm
            .map(|algorithm| algorithm.security_has_data(&security.symbol))
            .unwrap_or(security.price > Decimal::ZERO)
    }

    pub fn security_is_tradable(&self, security: &SecurityData) -> bool {
        self.algorithm
            .map(|algorithm| algorithm.security_is_tradable(&security.symbol))
            .unwrap_or(true)
    }

    pub fn authoritative_projected_quantity(
        &self,
        symbol: &Symbol,
        security: &SecurityData,
    ) -> Decimal {
        self.algorithm
            .map(|algorithm| algorithm.projected_quantity(symbol))
            .unwrap_or_else(|| self.projected_quantity(symbol, security))
    }

    pub fn authoritative_holdings_quantity(&self, security: &SecurityData) -> Decimal {
        self.algorithm
            .map(|algorithm| algorithm.holdings_quantity(&security.symbol))
            .unwrap_or(security.current_quantity)
    }

    pub fn security(&self, symbol: &Symbol) -> Option<&SecurityData> {
        self.securities.get(&symbol.id.sid)
    }

    pub fn open_orders_for_symbol<'b>(
        &'b self,
        symbol: &Symbol,
    ) -> impl Iterator<Item = &'b ExecutionOpenOrder> + 'b {
        let sid = symbol.id.sid;
        self.open_orders
            .iter()
            .filter(move |order| order.symbol.id.sid == sid)
    }

    pub fn open_order_quantity(&self, symbol: &Symbol) -> Decimal {
        self.open_orders_for_symbol(symbol)
            .map(|order| order.remaining_quantity)
            .sum()
    }

    pub fn projected_open_order_quantity(
        &self,
        symbol: &Symbol,
        security: &SecurityData,
    ) -> Decimal {
        if self.open_orders.is_empty() {
            security.open_order_quantity
        } else {
            self.open_order_quantity(symbol)
        }
    }

    pub fn projected_quantity(&self, symbol: &Symbol, security: &SecurityData) -> Decimal {
        security.current_quantity + self.projected_open_order_quantity(symbol, security)
    }

    pub fn unordered_quantity(
        &self,
        symbol: &Symbol,
        security: &SecurityData,
        target_quantity: Decimal,
    ) -> Decimal {
        adjust_by_lot_size(
            security.lot_size,
            target_quantity - self.projected_quantity(symbol, security),
        )
    }

    pub fn actual_holding_delta(
        &self,
        security: &SecurityData,
        target_quantity: Decimal,
    ) -> Decimal {
        adjust_by_lot_size(
            security.lot_size,
            target_quantity - security.current_quantity,
        )
    }

    pub fn order_targets_by_margin_impact(
        &self,
        targets: &[(u64, Symbol, Decimal)],
    ) -> Vec<(u64, Symbol, Decimal)> {
        let mut filtered = targets
            .iter()
            .filter_map(|target| {
                let security = self.security(&target.1)?;
                let unordered = self.unordered_quantity(&target.1, security, target.2);
                if unordered.abs() < security.lot_size {
                    None
                } else {
                    Some(target.clone())
                }
            })
            .collect::<Vec<_>>();

        self.sort_targets_by_margin_impact(&mut filtered);
        filtered
    }

    pub fn sort_targets_by_margin_impact(&self, targets: &mut [(u64, Symbol, Decimal)]) {
        targets.sort_by(|left, right| {
            let left_impact = margin_impact(left, self);
            let right_impact = margin_impact(right, self);

            right_impact
                .is_reducing_position
                .cmp(&left_impact.is_reducing_position)
                .then_with(|| {
                    right_impact
                        .order_value
                        .partial_cmp(&left_impact.order_value)
                        .unwrap_or(Ordering::Equal)
                })
                .then_with(|| left.1.value.cmp(&right.1.value))
        });
    }
}

/// Converts portfolio targets into orders. Mirrors C# IExecutionModel.
pub trait IExecutionModel: Send + Sync {
    fn execute(
        &mut self,
        targets: &[ExecutionTarget],
        context: &ExecutionContext<'_>,
    ) -> Vec<OrderRequest>;

    fn execute_with_context(
        &mut self,
        targets: &[ExecutionTarget],
        context: &ExecutionContext<'_>,
    ) -> Vec<OrderRequest> {
        self.execute(targets, context)
    }

    fn execute_refs_with_context(
        &mut self,
        targets: &[ExecutionTargetRef<'_>],
        context: &ExecutionContext<'_>,
    ) -> Vec<OrderRequest> {
        let owned: Vec<ExecutionTarget> = targets
            .iter()
            .map(|target| ExecutionTarget {
                symbol: target.symbol.clone(),
                quantity: target.quantity,
                tag: target.tag.to_string(),
            })
            .collect();
        self.execute_with_context(&owned, context)
    }

    fn on_securities_changed(&mut self, _added: &[Symbol], _removed: &[Symbol]) {}
    fn name(&self) -> &str {
        "ExecutionModel"
    }
}
