[package]
name = "rlean-statistics"
version.workspace = true
edition.workspace = true
description = "Backtest result statistics for rlean."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rlean-core = { path = "../rlean-core", version = "0.1.1" }
serde = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
statrs = { workspace = true }
thiserror = { workspace = true }
