use crate::portfolio::SecurityPortfolioManager;
use std::sync::Arc;

use super::context::MarginCallContext;

/// A liquidation order generated by the margin call model.
#[derive(Debug, Clone)]
pub struct MarginCallOrderRequest {
    pub symbol: lean_core::Symbol,
    pub quantity: rust_decimal::Decimal,
    pub tag: &'static str,
}

impl MarginCallOrderRequest {
    pub const TAG: &'static str = "Margin Call";

    pub fn new(symbol: lean_core::Symbol, quantity: rust_decimal::Decimal) -> Self {
        Self {
            symbol,
            quantity,
            tag: Self::TAG,
        }
    }
}

/// Picks and executes orders during a margin call — mirrors C# `IMarginCallModel`.
pub trait MarginCallModel {
    fn get_margin_call_orders(
        &self,
        ctx: &MarginCallContext,
    ) -> (Vec<MarginCallOrderRequest>, bool);
}

/// Live-mode no-op margin call model — mirrors C# `MarginCallModel.Null`.
#[derive(Debug, Clone, Copy, Default)]
pub struct NullMarginCallModel;

impl MarginCallModel for NullMarginCallModel {
    fn get_margin_call_orders(
        &self,
        _ctx: &MarginCallContext,
    ) -> (Vec<MarginCallOrderRequest>, bool) {
        (Vec::new(), false)
    }
}

/// Stored margin call model kind on the portfolio.
#[derive(Debug, Clone)]
pub enum MarginCallModelKind {
    Default(super::default_model::DefaultMarginCallModel),
    Null(NullMarginCallModel),
}

impl MarginCallModelKind {
    pub fn default_backtest() -> Self {
        MarginCallModelKind::Default(super::default_model::DefaultMarginCallModel::new())
    }

    pub fn live_disabled() -> Self {
        MarginCallModelKind::Null(NullMarginCallModel)
    }

    pub fn is_null(&self) -> bool {
        matches!(self, MarginCallModelKind::Null(_))
    }
}

impl MarginCallModel for MarginCallModelKind {
    fn get_margin_call_orders(
        &self,
        ctx: &MarginCallContext,
    ) -> (Vec<MarginCallOrderRequest>, bool) {
        match self {
            MarginCallModelKind::Default(model) => model.get_margin_call_orders(ctx),
            MarginCallModelKind::Null(model) => model.get_margin_call_orders(ctx),
        }
    }
}

/// Execution context for synchronous margin-call fills.
pub struct MarginCallExecutionContext<'a> {
    pub portfolio: &'a Arc<SecurityPortfolioManager>,
    pub algorithm: &'a mut crate::qc_algorithm::QcAlgorithm,
    pub order_processor: &'a lean_orders::order_processor::OrderProcessor,
    pub time: lean_core::DateTime,
    pub trade_bars: &'a std::collections::HashMap<u64, lean_data::TradeBar>,
    pub quote_bars: &'a std::collections::HashMap<u64, lean_data::QuoteBar>,
    pub total_margin_used: rust_decimal::Decimal,
}

impl MarginCallExecutionContext<'_> {
    pub fn margin_remaining(&self) -> rust_decimal::Decimal {
        let tpv = self.portfolio.total_portfolio_value();
        self.portfolio
            .margin_remaining_for_value(tpv, self.total_margin_used)
    }

    pub fn refresh_total_margin_used(&mut self) {
        self.total_margin_used = self.algorithm.total_margin_used();
    }
}
