use lean_core::{DateTime, Symbol};
use rust_decimal::Decimal;
use std::{cmp::Ordering, collections::HashMap};

/// Simplified portfolio target for execution (avoids depending on lean-portfolio-construction)
#[derive(Debug, Clone)]
pub struct ExecutionTarget {
    pub symbol: Symbol,
    /// Desired quantity (positive = long, negative = short, 0 = liquidate)
    pub quantity: Decimal,
}

/// An order request generated by execution
#[derive(Debug, Clone)]
pub struct OrderRequest {
    pub order_id: Option<i64>,
    pub symbol: Symbol,
    pub quantity: Decimal,
    pub order_type: ExecutionOrderType,
    pub limit_price: Option<Decimal>,
    pub post_only: bool,
    pub cancel_open_orders: bool,
    pub tag: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionOrderType {
    Market,
    Limit,
    MarketOnOpen,
    MarketOnClose,
    Cancel,
    Update,
}

#[derive(Debug, Clone)]
pub struct ExecutionOpenOrder {
    pub id: i64,
    pub symbol: Symbol,
    pub quantity: Decimal,
    pub filled_quantity: Decimal,
    pub remaining_quantity: Decimal,
    pub order_type: ExecutionOrderType,
    pub limit_price: Option<Decimal>,
    pub post_only: bool,
    pub tag: String,
    pub created_time: DateTime,
    pub last_update_time: Option<DateTime>,
}

/// Current security data needed by execution models
#[derive(Debug, Clone)]
pub struct SecurityData {
    pub symbol: Symbol,
    pub price: Decimal,
    pub bid: Option<Decimal>,
    pub ask: Option<Decimal>,
    /// Current trade volume used by Lean's percent-volume order sizing.
    pub volume: Option<Decimal>,
    /// Average trade price for the current VWAP input, if trade data is present.
    pub vwap_price: Option<Decimal>,
    pub average_volume: Option<Decimal>,
    pub daily_std_dev: Option<Decimal>,
    pub end_time: Option<DateTime>,
    pub lot_size: Decimal,
    pub minimum_price_variation: Decimal,
    pub current_quantity: Decimal, // currently held
    pub open_order_quantity: Decimal,
}

/// Algorithm-aware execution context.
///
/// C# LEAN passes the full QCAlgorithm instance into IExecutionModel.Execute.
/// rlean keeps execution models in a lower-level crate, so this context is the
/// framework boundary: time, securities, portfolio state, and transaction state
/// are passed together instead of as a reduced security snapshot.
pub struct ExecutionContext<'a> {
    pub time: DateTime,
    pub securities: &'a HashMap<String, SecurityData>,
    pub open_orders: &'a [ExecutionOpenOrder],
    pub portfolio_value: Decimal,
}

/// Sorts targets using the same high-level priority as C# LEAN's
/// `PortfolioTargetCollection.OrderByMarginImpact`: position-reducing orders
/// first, then the largest remaining order value.
pub fn sort_targets_by_margin_impact(
    targets: &mut [(String, Symbol, Decimal)],
    securities: &HashMap<String, SecurityData>,
) {
    let open_orders = Vec::new();
    let context = ExecutionContext::new(DateTime::MIN, securities, &open_orders, Decimal::ZERO);
    context.sort_targets_by_margin_impact(targets);
}

#[derive(Debug, Clone, Copy)]
struct MarginImpact {
    is_reducing_position: bool,
    order_value: Decimal,
}

fn margin_impact(
    target: &(String, Symbol, Decimal),
    context: &ExecutionContext<'_>,
) -> MarginImpact {
    let Some(security) = context.securities.get(&target.0) else {
        return MarginImpact {
            is_reducing_position: false,
            order_value: Decimal::ZERO,
        };
    };

    let target_quantity = adjust_by_lot_size(security.lot_size, target.2);
    let existing_quantity = context.projected_quantity(&target.1, security);
    let unordered_quantity = target_quantity - existing_quantity;
    let is_reducing_position =
        existing_quantity != Decimal::ZERO && target_quantity.abs() < existing_quantity.abs();
    let price = if security.price > Decimal::ZERO {
        security.price
    } else {
        Decimal::ZERO
    };

    MarginImpact {
        is_reducing_position,
        order_value: (unordered_quantity * price).abs(),
    }
}

pub fn adjust_by_lot_size(lot_size: Decimal, quantity: Decimal) -> Decimal {
    if lot_size <= Decimal::ZERO || quantity == Decimal::ZERO {
        return quantity;
    }

    let abs_quantity = quantity.abs();
    let mut remainder = abs_quantity % lot_size;
    let missing_for_lot_size = lot_size - remainder;
    if missing_for_lot_size < lot_size / Decimal::from(1_000_000u64) {
        remainder -= lot_size;
    }

    let sign = if quantity < Decimal::ZERO {
        -Decimal::ONE
    } else {
        Decimal::ONE
    };
    (abs_quantity - remainder) * sign
}

impl<'a> ExecutionContext<'a> {
    pub fn new(
        time: DateTime,
        securities: &'a HashMap<String, SecurityData>,
        open_orders: &'a [ExecutionOpenOrder],
        portfolio_value: Decimal,
    ) -> Self {
        Self {
            time,
            securities,
            open_orders,
            portfolio_value,
        }
    }

    pub fn security(&self, symbol: &Symbol) -> Option<&SecurityData> {
        self.securities.get(&symbol.value)
    }

    pub fn open_orders_for_symbol<'b>(
        &'b self,
        symbol: &Symbol,
    ) -> impl Iterator<Item = &'b ExecutionOpenOrder> + 'b {
        let sid = symbol.id.sid;
        self.open_orders
            .iter()
            .filter(move |order| order.symbol.id.sid == sid)
    }

    pub fn open_order_quantity(&self, symbol: &Symbol) -> Decimal {
        self.open_orders_for_symbol(symbol)
            .map(|order| order.remaining_quantity)
            .sum()
    }

    pub fn projected_open_order_quantity(
        &self,
        symbol: &Symbol,
        security: &SecurityData,
    ) -> Decimal {
        if self.open_orders.is_empty() {
            security.open_order_quantity
        } else {
            self.open_order_quantity(symbol)
        }
    }

    pub fn projected_quantity(&self, symbol: &Symbol, security: &SecurityData) -> Decimal {
        security.current_quantity + self.projected_open_order_quantity(symbol, security)
    }

    pub fn unordered_quantity(
        &self,
        symbol: &Symbol,
        security: &SecurityData,
        target_quantity: Decimal,
    ) -> Decimal {
        adjust_by_lot_size(
            security.lot_size,
            target_quantity - self.projected_quantity(symbol, security),
        )
    }

    pub fn actual_holding_delta(
        &self,
        security: &SecurityData,
        target_quantity: Decimal,
    ) -> Decimal {
        adjust_by_lot_size(
            security.lot_size,
            target_quantity - security.current_quantity,
        )
    }

    pub fn order_targets_by_margin_impact(
        &self,
        targets: &[(String, Symbol, Decimal)],
    ) -> Vec<(String, Symbol, Decimal)> {
        let mut filtered = targets
            .iter()
            .filter_map(|target| {
                let security = self.securities.get(&target.0)?;
                let unordered = self.unordered_quantity(&target.1, security, target.2);
                if unordered.abs() < security.lot_size {
                    None
                } else {
                    Some(target.clone())
                }
            })
            .collect::<Vec<_>>();

        self.sort_targets_by_margin_impact(&mut filtered);
        filtered
    }

    pub fn sort_targets_by_margin_impact(&self, targets: &mut [(String, Symbol, Decimal)]) {
        targets.sort_by(|left, right| {
            let left_impact = margin_impact(left, self);
            let right_impact = margin_impact(right, self);

            right_impact
                .is_reducing_position
                .cmp(&left_impact.is_reducing_position)
                .then_with(|| {
                    right_impact
                        .order_value
                        .partial_cmp(&left_impact.order_value)
                        .unwrap_or(Ordering::Equal)
                })
                .then_with(|| left.1.value.cmp(&right.1.value))
        });
    }
}

/// Converts portfolio targets into orders. Mirrors C# IExecutionModel.
pub trait IExecutionModel: Send + Sync {
    fn execute(
        &mut self,
        targets: &[ExecutionTarget],
        securities: &HashMap<String, SecurityData>,
    ) -> Vec<OrderRequest> {
        let open_orders = Vec::new();
        let context = ExecutionContext::new(DateTime::MIN, securities, &open_orders, Decimal::ZERO);
        self.execute_with_context(targets, &context)
    }

    fn execute_with_context(
        &mut self,
        targets: &[ExecutionTarget],
        context: &ExecutionContext<'_>,
    ) -> Vec<OrderRequest> {
        self.execute(targets, context.securities)
    }

    fn on_securities_changed(&mut self, _added: &[Symbol], _removed: &[Symbol]) {}
    fn name(&self) -> &str {
        "ExecutionModel"
    }
}
