use lean_core::{DateTime, Symbol};
use rust_decimal::Decimal;
use std::collections::HashMap;

/// Simplified portfolio target for execution (avoids depending on lean-portfolio-construction)
#[derive(Debug, Clone)]
pub struct ExecutionTarget {
    pub symbol: Symbol,
    /// Desired quantity (positive = long, negative = short, 0 = liquidate)
    pub quantity: Decimal,
}

/// An order request generated by execution
#[derive(Debug, Clone)]
pub struct OrderRequest {
    pub symbol: Symbol,
    pub quantity: Decimal,
    pub order_type: ExecutionOrderType,
    pub limit_price: Option<Decimal>,
    pub post_only: bool,
    pub cancel_open_orders: bool,
    pub tag: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionOrderType {
    Market,
    Limit,
    MarketOnOpen,
    MarketOnClose,
    Cancel,
}

/// Current security data needed by execution models
#[derive(Debug, Clone)]
pub struct SecurityData {
    pub symbol: Symbol,
    pub price: Decimal,
    pub bid: Option<Decimal>,
    pub ask: Option<Decimal>,
    /// Current trade volume used by Lean's percent-volume order sizing.
    pub volume: Option<Decimal>,
    /// Average trade price for the current VWAP input, if trade data is present.
    pub vwap_price: Option<Decimal>,
    pub average_volume: Option<Decimal>,
    pub daily_std_dev: Option<Decimal>,
    pub end_time: Option<DateTime>,
    pub lot_size: Decimal,
    pub current_quantity: Decimal, // currently held
    pub open_order_quantity: Decimal,
}

/// Converts portfolio targets into orders. Mirrors C# IExecutionModel.
pub trait IExecutionModel: Send + Sync {
    fn execute(
        &mut self,
        targets: &[ExecutionTarget],
        securities: &HashMap<String, SecurityData>,
    ) -> Vec<OrderRequest>;

    fn on_securities_changed(&mut self, _added: &[Symbol], _removed: &[Symbol]) {}
    fn name(&self) -> &str {
        "ExecutionModel"
    }
}
