/// `rlean stubs create` — generate AlgorithmImports.pyi stub files and install
/// them into the active Python environment so IDEs get autocomplete for Lean
/// strategies.
///
/// The stubs are authored directly from the PyO3 source (see
/// `crates/lean-python/src/`).  They are updated whenever `rlean` is rebuilt.
use std::path::PathBuf;
use std::process::Command as SysCommand;

use anyhow::{Context, Result};
use clap::Subcommand;

// ─── CLI args ─────────────────────────────────────────────────────────────────

#[derive(clap::Args)]
pub struct StubsArgs {
    #[command(subcommand)]
    pub command: StubsCommand,
}

#[derive(Subcommand)]
pub enum StubsCommand {
    /// Generate AlgorithmImports.pyi and install it into the active Python
    /// environment (site-packages) and the current working directory.
    Create {
        /// Override the output directory.  When omitted the stubs are written
        /// to both `python3 site-packages` and the current working directory.
        #[arg(long)]
        output: Option<PathBuf>,
    },
}

// ─── Stub content ─────────────────────────────────────────────────────────────

/// The full `AlgorithmImports.pyi` content, derived directly from the PyO3
/// source files in `crates/lean-python/src/`.
const STUB_CONTENT: &str = r#"# AlgorithmImports.pyi
# Auto-generated by `rlean stubs create`.
# Do not edit by hand — regenerate with `rlean stubs create` after rebuilding.
from __future__ import annotations
from datetime import datetime
from typing import Any, Callable, List, Optional, Tuple

# ── DataNormalizationMode ─────────────────────────────────────────────────────

class DataNormalizationMode:
    """Controls how historical prices are adjusted for splits and dividends."""

    Raw: DataNormalizationMode
    Adjusted: DataNormalizationMode
    SplitAdjusted: DataNormalizationMode
    TotalReturn: DataNormalizationMode
    ForwardPanamaCanal: DataNormalizationMode
    BackwardPanamaCanal: DataNormalizationMode

# ── MovingAverageType ─────────────────────────────────────────────────────────

class MovingAverageType:
    """Selects which smoothing method is used by an indicator."""

    Simple: MovingAverageType
    Exponential: MovingAverageType
    Weighted: MovingAverageType
    DoubleExponential: MovingAverageType
    TripleExponential: MovingAverageType
    Triangular: MovingAverageType
    Kama: MovingAverageType
    Adaptive: MovingAverageType
    LinearWeightedMovingAverage: MovingAverageType
    Alma: MovingAverageType
    T3: MovingAverageType
    Vwap: MovingAverageType
    Hull: MovingAverageType

# ── Resolution ────────────────────────────────────────────────────────────────

class Resolution:
    """LEAN Resolution enum (PascalCase variants).

    Usage::

        self.add_equity("SPY", Resolution.Daily)
    """

    Tick: Resolution
    Second: Resolution
    Minute: Resolution
    Hour: Resolution
    Daily: Resolution

# ── SecurityType ──────────────────────────────────────────────────────────────

class SecurityType:
    """LEAN SecurityType enum."""

    Base: SecurityType
    Equity: SecurityType
    Option: SecurityType
    Forex: SecurityType
    Future: SecurityType
    Cfd: SecurityType
    Crypto: SecurityType
    Index: SecurityType

# ── OrderType ─────────────────────────────────────────────────────────────────

class OrderType:
    """LEAN OrderType enum."""

    Market: OrderType
    Limit: OrderType
    StopMarket: OrderType
    StopLimit: OrderType
    MarketOnClose: OrderType
    OptionExercise: OrderType
    LimitIfTouched: OrderType
    ComboMarket: OrderType
    ComboLimit: OrderType
    ComboLegLimit: OrderType
    TrailingStop: OrderType

# ── OrderStatus ───────────────────────────────────────────────────────────────

class OrderStatus:
    """LEAN OrderStatus enum."""

    New: OrderStatus
    Submitted: OrderStatus
    PartiallyFilled: OrderStatus
    Filled: OrderStatus
    Canceled: OrderStatus
    Invalid: OrderStatus
    CancelPending: OrderStatus
    UpdateSubmitted: OrderStatus

# ── OptionRight ───────────────────────────────────────────────────────────────

class OptionRight:
    """Call or Put option right."""

    Call: OptionRight
    Put: OptionRight

    def is_call(self) -> bool: ...
    def is_put(self) -> bool: ...

# ── Symbol ────────────────────────────────────────────────────────────────────

class Symbol:
    """Immutable identifier for a tradeable security."""

    @property
    def value(self) -> str:
        """Canonical symbol string (e.g. 'SPY')."""
        ...

    @property
    def ticker(self) -> str:
        """Permanent ticker (permtick)."""
        ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

# ── Security ──────────────────────────────────────────────────────────────────

class Security:
    """Returned by ``add_equity`` / ``add_forex`` / ``add_crypto``.

    Usage::

        spy_security = self.add_equity("SPY", Resolution.Daily)
        self.spy = spy_security.symbol   # Symbol
    """

    @property
    def symbol(self) -> Symbol: ...

# ── IndicatorResult ───────────────────────────────────────────────────────────

class IndicatorResult:
    """Result of a single indicator ``update`` call."""

    is_ready: bool
    value: float

# ── IndicatorDataPoint ────────────────────────────────────────────────────────

class IndicatorDataPoint:
    """Snapshot of an indicator's current output.

    Accessed via ``indicator.current``.
    """

    @property
    def value(self) -> float: ...

    @property
    def time(self) -> datetime: ...

# ── TradeBar ──────────────────────────────────────────────────────────────────

class TradeBar:
    """OHLCV bar for a single period."""

    open: float
    high: float
    low: float
    close: float
    volume: float
    symbol: Symbol
    time: str       # ISO 8601 open time
    end_time: str   # ISO 8601 close time

    def __repr__(self) -> str: ...

# ── TradeBars ─────────────────────────────────────────────────────────────────

class TradeBars:
    """Dict-like collection of TradeBar objects keyed by Symbol.

    Usage::

        bar = data.bars[self.spy]
        bar = data.bars.get(self.spy)   # returns None if missing
    """

    def __getitem__(self, symbol: Symbol | Security | str) -> Optional[TradeBar]: ...
    def get(self, symbol: Symbol | Security | str) -> Optional[TradeBar]: ...
    def __contains__(self, symbol: Symbol | Security | str) -> bool: ...
    def __len__(self) -> int: ...
    def values(self) -> List[TradeBar]: ...

# ── Slice ─────────────────────────────────────────────────────────────────────

class Slice:
    """Data container delivered to ``on_data(self, data)``."""

    has_data: bool

    @property
    def bars(self) -> TradeBars: ...

    def get_bar(self, symbol: Symbol | Security | str) -> Optional[TradeBar]: ...
    def get(self, symbol: Symbol | Security | str) -> Optional[TradeBar]: ...
    def __getitem__(self, symbol: Symbol | Security | str) -> Optional[TradeBar]: ...
    def tickers(self) -> List[str]: ...

# ── OrderEvent ────────────────────────────────────────────────────────────────

class OrderEvent:
    """Emitted when an order changes state (fill, cancel, etc.)."""

    order_id: int
    symbol: Symbol
    fill_price: float
    fill_quantity: float
    is_fill: bool
    message: str

# ── SecurityHolding ───────────────────────────────────────────────────────────

class SecurityHolding:
    """Current position in a single security."""

    symbol: Symbol
    quantity: float
    average_price: float
    unrealized_pnl: float
    realized_pnl: float
    total_fees: float
    last_price: float
    is_long: bool
    is_short: bool
    is_invested: bool
    market_value: float

    @property
    def invested(self) -> bool:
        """Alias for ``is_invested``."""
        ...

    @property
    def unrealized_profit(self) -> float:
        """Alias for ``unrealized_pnl``."""
        ...

    @property
    def profit(self) -> float:
        """Realized + unrealized P&L."""
        ...

# ── Portfolio ─────────────────────────────────────────────────────────────────

class Portfolio:
    """The algorithm's portfolio -- tracks cash, holdings, and total value."""

    @property
    def cash(self) -> float: ...

    @property
    def total_portfolio_value(self) -> float: ...

    @property
    def total_value(self) -> float:
        """Alias for ``total_portfolio_value``."""
        ...

    @property
    def unrealized_pnl(self) -> float: ...

    @property
    def total_holdings_value(self) -> float: ...

    @property
    def is_invested(self) -> bool:
        """True if any position is currently held."""
        ...

    def is_invested_in(self, symbol: Symbol) -> bool: ...
    def get_holding(self, symbol: Symbol) -> SecurityHolding: ...
    def holdings(self) -> List[SecurityHolding]: ...
    def __getitem__(self, symbol: Symbol | Security | str) -> SecurityHolding: ...

# ── Greeks ────────────────────────────────────────────────────────────────────

class Greeks:
    """Option Greeks."""

    delta: float
    gamma: float
    vega: float
    theta: float
    rho: float
    lambda_: float

    def theta_per_day(self) -> float: ...

# ── OptionContract ────────────────────────────────────────────────────────────

class OptionContract:
    """A single option contract in a chain."""

    @property
    def strike(self) -> float: ...
    @property
    def expiry(self) -> str: ...
    @property
    def right(self) -> OptionRight: ...
    @property
    def style(self) -> str: ...
    @property
    def underlying_price(self) -> float: ...
    @property
    def theoretical_price(self) -> float: ...
    @property
    def implied_volatility(self) -> float: ...
    @property
    def open_interest(self) -> float: ...
    @property
    def greeks(self) -> Greeks: ...
    @property
    def last_price(self) -> float: ...
    @property
    def bid_price(self) -> float: ...
    @property
    def ask_price(self) -> float: ...
    @property
    def mid_price(self) -> float: ...
    @property
    def volume(self) -> int: ...
    @property
    def ticker(self) -> str: ...

    def is_call(self) -> bool: ...
    def is_put(self) -> bool: ...
    def intrinsic_value(self) -> float: ...
    def time_value(self) -> float: ...

# ── OptionChain ───────────────────────────────────────────────────────────────

class OptionChain:
    """The full option chain for an underlying security."""

    @property
    def underlying(self) -> str: ...
    @property
    def underlying_price(self) -> float: ...

    def contracts(self) -> List[OptionContract]: ...
    def calls(self) -> List[OptionContract]: ...
    def puts(self) -> List[OptionContract]: ...
    def filter(self, filter_fn: Callable[[List[OptionContract]], List[OptionContract]]) -> List[OptionContract]: ...
    def where_expiry(self, min_days: int, max_days: int) -> List[OptionContract]: ...
    def where_strike(self, min_pct: float, max_pct: float) -> List[OptionContract]: ...
    def __len__(self) -> int: ...

# ── Indicators ────────────────────────────────────────────────────────────────

class SimpleMovingAverage:
    """Simple Moving Average (SMA).

    Usage::

        sma = SimpleMovingAverage(50)
        sma.update(self.time, bar.close)
        if sma.is_ready:
            print(sma.current.value)
    """

    def __init__(self, period: int) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def samples(self) -> int: ...
    @property
    def warm_up_period(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint: ...

    def update(self, time_or_value: Any, value: Optional[float] = None) -> IndicatorResult: ...
    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

class ExponentialMovingAverage:
    """Exponential Moving Average (EMA).

    Usage::

        ema = ExponentialMovingAverage(20)
        ema.update(self.time, bar.close)
    """

    def __init__(self, period: int) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def samples(self) -> int: ...
    @property
    def warm_up_period(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint: ...

    def update(self, time_or_value: Any, value: Optional[float] = None) -> IndicatorResult: ...
    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

class RelativeStrengthIndex:
    """Relative Strength Index (RSI).

    Usage::

        rsi = RelativeStrengthIndex(14)
        rsi.update(self.time, bar.close)
        if rsi.is_ready and rsi.is_overbought:
            self.liquidate()
    """

    def __init__(self, period: int) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def is_overbought(self) -> bool: ...
    @property
    def is_oversold(self) -> bool: ...
    @property
    def samples(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint: ...

    def update(self, time_or_value: Any, value: Optional[float] = None) -> IndicatorResult: ...
    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

class MovingAverageConvergenceDivergence:
    """Moving Average Convergence/Divergence (MACD).

    Usage::

        macd = MovingAverageConvergenceDivergence(12, 26, 9)
        macd.update(self.time, bar.close)
        if macd.is_ready:
            line = macd.macd_line
            sig  = macd.signal_line
            hist = macd.histogram
    """

    def __init__(self, fast: int, slow: int, signal: int) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def macd_line(self) -> float: ...
    @property
    def signal_line(self) -> float: ...
    @property
    def histogram(self) -> float: ...
    @property
    def samples(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint: ...

    def update(self, time_or_value: Any, value: Optional[float] = None) -> IndicatorResult: ...
    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

class BollingerBands:
    """Bollinger Bands indicator.

    Usage::

        bb = BollingerBands(20)           # default k=2.0
        bb = BollingerBands(20, k=2.5)
        bb.update(self.time, bar.close)
        if bb.is_ready:
            print(bb.upper, bb.middle, bb.lower)
    """

    def __init__(self, period: int, k: float = 2.0) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def middle(self) -> float: ...
    @property
    def upper(self) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def bandwidth(self) -> float: ...
    @property
    def percent_b(self) -> float: ...
    @property
    def samples(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint:
        """Returns an IndicatorDataPoint whose ``value`` is the middle band."""
        ...

    def update(self, time_or_value: Any, value: Optional[float] = None) -> IndicatorResult: ...
    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

class AverageTrueRange:
    """Average True Range (ATR).

    ATR requires OHLC data -- use ``update_bar`` rather than ``update``.

    Usage::

        atr = AverageTrueRange(14)
        atr.update_bar(bar)
        if atr.is_ready:
            print(atr.current.value)
    """

    def __init__(self, period: int) -> None: ...

    @property
    def is_ready(self) -> bool: ...
    @property
    def value(self) -> float: ...
    @property
    def samples(self) -> int: ...
    @property
    def current(self) -> IndicatorDataPoint: ...

    def update_bar(self, bar: TradeBar) -> IndicatorResult: ...
    def reset(self) -> None: ...

# ── Algorithm Framework — Insight types ──────────────────────────────────────

class InsightDirection:
    """Direction of an alpha insight."""
    Up: InsightDirection
    Flat: InsightDirection
    Down: InsightDirection

class Insight:
    """A single alpha signal emitted by an AlphaModel.

    Usage::

        from datetime import timedelta
        Insight(symbol, InsightDirection.Up, timedelta(days=1))
        Insight.price(symbol, timedelta(days=1), InsightDirection.Up)
    """

    symbol: Symbol
    direction: InsightDirection

    def __init__(
        self,
        symbol: Symbol | str,
        direction: InsightDirection,
        period: Any,
        magnitude: Optional[float] = None,
        confidence: Optional[float] = None,
        source_model: Optional[str] = None,
    ) -> None: ...

    @staticmethod
    def price(
        symbol: Symbol | str,
        period: Any,
        direction: InsightDirection,
        magnitude: Optional[float] = None,
        confidence: Optional[float] = None,
        source_model: Optional[str] = None,
    ) -> Insight: ...

    @staticmethod
    def Price(
        symbol: Symbol | str,
        period: Any,
        direction: InsightDirection,
        magnitude: Optional[float] = None,
        confidence: Optional[float] = None,
        source_model: Optional[str] = None,
    ) -> Insight:
        """LEAN PascalCase alias for :meth:`price`."""
        ...

# ── Algorithm Framework — Base Classes ────────────────────────────────────────

class AlphaModel:
    """Base class for Python-defined alpha models.

    Subclass and override ``Update`` to emit :class:`Insight` objects
    (LEAN uses PascalCase to match the C# API)::

        class MyAlpha(AlphaModel):
            def Update(self, algorithm, data):
                return [Insight.Price(symbol, timedelta(days=1), InsightDirection.Up)]
    """

    def Update(self, algorithm: QCAlgorithm, data: Slice) -> List[Insight]: ...
    def OnSecuritiesChanged(self, algorithm: QCAlgorithm, changes: Any) -> None: ...

class PortfolioConstructionModel:
    """Base class for Python-defined portfolio construction models."""

class ExecutionModel:
    """Base class for Python-defined execution models."""

class RiskManagementModel:
    """Base class for Python-defined risk management models."""

# ── Algorithm Framework — Alpha Models ────────────────────────────────────────

class ConstantAlphaModel(AlphaModel):
    """Emits a constant directional insight for all subscribed securities."""
    def __init__(self, direction: str, period_days: int, magnitude: Optional[float] = None) -> None: ...

class EmaCrossAlphaModel(AlphaModel):
    """EMA cross-over alpha model."""
    def __init__(self, fast_period: int = 50, slow_period: int = 200, period_days: int = 1) -> None: ...

class MacdAlphaModel(AlphaModel):
    """MACD-based alpha model."""
    def __init__(self, fast_period: int = 12, slow_period: int = 26, signal_period: int = 9, period_days: int = 1) -> None: ...

class RsiAlphaModel(AlphaModel):
    """RSI mean-reversion alpha model."""
    def __init__(self, period: int = 14, period_days: int = 1) -> None: ...

class HistoricalReturnsAlphaModel(AlphaModel):
    """Historical returns momentum/mean-reversion alpha model."""
    def __init__(self, period: int = 1, insight_period_days: Optional[int] = None) -> None: ...

class PearsonCorrelationPairsTradingAlphaModel(AlphaModel):
    """Pearson correlation pairs trading alpha model."""
    def __init__(self, lookback: int = 15, threshold: float = 1.0, minimum_correlation: float = 0.5, insight_period_days: Optional[int] = None) -> None: ...

# ── PortfolioBias ─────────────────────────────────────────────────────────────

class PortfolioBias:
    """Controls whether a PCM may hold short positions."""

    Short: PortfolioBias
    LongShort: PortfolioBias
    Long: PortfolioBias

# ── Algorithm Framework — Portfolio Construction Models ───────────────────────

class EqualWeightingPortfolioConstructionModel(PortfolioConstructionModel):
    """Equal-weight PCM: splits portfolio evenly across all Up-insight symbols."""
    def __init__(self) -> None: ...

class InsightWeightingPortfolioConstructionModel(PortfolioConstructionModel):
    """Weights positions by insight magnitude."""
    def __init__(self) -> None: ...

class MeanVarianceOptimizationPortfolioConstructionModel(PortfolioConstructionModel):
    """Mean-variance optimization PCM."""
    def __init__(self) -> None: ...

class MaximumSharpeRatioPortfolioConstructionModel(PortfolioConstructionModel):
    """Maximizes portfolio Sharpe ratio."""
    def __init__(self) -> None: ...

class BlackLittermanOptimizationPortfolioConstructionModel(PortfolioConstructionModel):
    """Black-Litterman portfolio construction model."""
    def __init__(
        self,
        rebalance: Any = None,
        portfolio_bias: PortfolioBias = ...,
        lookback: int = 1,
        period: int = 63,
        resolution: Resolution = ...,
        risk_free_rate: float = 0.0,
        delta: float = 2.5,
        tau: float = 0.05,
    ) -> None: ...

class RiskParityPortfolioConstructionModel(PortfolioConstructionModel):
    """Risk parity (equal risk contribution) PCM."""
    def __init__(self, lookback: int = 1, period: int = 252) -> None: ...

class ConfidenceWeightedPortfolioConstructionModel(PortfolioConstructionModel):
    """Weights positions by insight confidence."""
    def __init__(self) -> None: ...

class AccumulativeInsightPortfolioConstructionModel(PortfolioConstructionModel):
    """Accumulates per-insight allocations."""
    def __init__(self, percent: float = 0.03) -> None: ...

class MeanReversionPortfolioConstructionModel(PortfolioConstructionModel):
    """OLMAR mean-reversion PCM."""
    def __init__(self, reversion_threshold: float = 1.0, window_size: int = 20) -> None: ...

# ── Algorithm Framework — Execution Models ────────────────────────────────────

class ImmediateExecutionModel(ExecutionModel):
    """Submits market orders immediately."""
    def __init__(self) -> None: ...

class NullExecutionModel(ExecutionModel):
    """No-op execution model (for testing)."""
    def __init__(self) -> None: ...

class VolumeWeightedAveragePriceExecutionModel(ExecutionModel):
    """VWAP execution — slices orders by volume participation rate."""
    def __init__(self, participation_rate: float = 0.2) -> None: ...

class SpreadExecutionModel(ExecutionModel):
    """Only executes when bid-ask spread is within an acceptable threshold."""
    def __init__(self, accepting_spread_percent: float = 0.005) -> None: ...

class StandardDeviationExecutionModel(ExecutionModel):
    """Executes when price deviates by N standard deviations from mean."""
    def __init__(self, period: int = 60, deviations: float = 2.0) -> None: ...

# ── Algorithm Framework — Risk Management Models ──────────────────────────────

class NullRiskManagementModel(RiskManagementModel):
    """Pass-through — no risk adjustments."""
    def __init__(self) -> None: ...

class MaximumDrawdownPercentPerSecurity(RiskManagementModel):
    """Liquidates a security when its drawdown exceeds a threshold."""
    def __init__(self, maximum_drawdown_percent: float = 0.05) -> None: ...

class TrailingStopRiskManagementModel(RiskManagementModel):
    """Trailing stop — exits when price falls X% from the high-water mark."""
    def __init__(self, trailing_amount: float = 0.05) -> None: ...

class MaximumSectorExposureRiskManagementModel(RiskManagementModel):
    """Caps portfolio exposure to any single sector."""
    def __init__(self, maximum_sector_exposure: float = 0.20) -> None: ...

class MaximumDrawdownPercentPortfolio(RiskManagementModel):
    """Liquidates all holdings when portfolio drawdown exceeds a threshold."""
    def __init__(self, maximum_drawdown_percent: float = 0.05, is_trailing: bool = False) -> None: ...

class MaximumUnrealizedProfitPercentPerSecurity(RiskManagementModel):
    """Takes profit when a security's unrealized gain exceeds a threshold."""
    def __init__(self, maximum_unrealized_profit_percent: float = 0.05) -> None: ...

# ── QCAlgorithm ───────────────────────────────────────────────────────────────

class QCAlgorithm:
    """Base class for all Lean strategies.

    Subclass this and implement ``initialize`` and ``on_data``::

        from AlgorithmImports import *

        class MyStrategy(QCAlgorithm):
            def initialize(self):
                self.set_start_date(2020, 1, 1)
                self.set_end_date(2023, 12, 31)
                self.set_cash(100_000)
                self.spy = self.add_equity("SPY", Resolution.Daily).symbol
                self.sma50  = SimpleMovingAverage(50)
                self.sma200 = SimpleMovingAverage(200)

            def on_data(self, data: Slice):
                bar = data.bars.get(self.spy)
                if bar is None:
                    return
                self.sma50.update(self.time, bar.close)
                self.sma200.update(self.time, bar.close)
                if not self.sma50.is_ready or not self.sma200.is_ready:
                    return
                if self.sma50.current.value > self.sma200.current.value:
                    if not self.portfolio[self.spy].invested:
                        self.set_holdings(self.spy, 1.0)
                else:
                    self.liquidate()
    """

    # ── Time ──────────────────────────────────────────────────────────────────

    @property
    def time(self) -> datetime:
        """Current algorithm time in the exchange timezone."""
        ...

    @property
    def utc_time(self) -> datetime:
        """Current algorithm time in UTC."""
        ...

    @property
    def is_warming_up(self) -> bool:
        """True during the warm-up period."""
        ...

    # ── Portfolio ─────────────────────────────────────────────────────────────

    @property
    def portfolio(self) -> Portfolio: ...

    @property
    def cash(self) -> float:
        """Current uninvested cash balance."""
        ...

    @property
    def portfolio_value(self) -> float:
        """Total portfolio value (cash + holdings)."""
        ...

    def is_invested(self, symbol: Symbol | Security | str) -> bool: ...

    # ── Configuration ─────────────────────────────────────────────────────────

    def set_start_date(self, year: int, month: int, day: int) -> None: ...
    def set_end_date(self, year: int, month: int, day: int) -> None: ...
    def set_cash(self, amount: float) -> None: ...
    def add_cash(self, amount: float) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_warm_up(self, bars_or_days: int) -> None: ...

    # ── Universe subscription ─────────────────────────────────────────────────

    def add_equity(self, ticker: str, resolution: Resolution = ...) -> Security: ...
    def add_forex(self, ticker: str, resolution: Resolution = ...) -> Security: ...
    def add_crypto(self, ticker: str, resolution: Resolution = ...) -> Security: ...

    # ── Options ───────────────────────────────────────────────────────────────

    def add_option(self, ticker: str, resolution: Optional[str] = None) -> str:
        """Subscribe to an option chain.

        Returns the canonical option ticker string (e.g. ``'?SPY'``).
        """
        ...

    def get_option_chain(self, canonical_ticker: str) -> Optional[OptionChain]: ...
    def sell_to_open(self, contract: OptionContract, quantity: float, premium: float) -> int: ...
    def buy_to_open(self, contract: OptionContract, quantity: float, premium: float) -> int: ...
    def buy_to_close(self, contract: OptionContract, quantity: float, premium: float) -> int: ...
    def sell_to_close(self, contract: OptionContract, quantity: float, premium: float) -> int: ...
    def get_option_positions(self) -> List[Any]: ...

    # ── Ordering ──────────────────────────────────────────────────────────────

    def market_order(self, symbol: Symbol | Security | str, quantity: float) -> None: ...
    def limit_order(self, symbol: Symbol | Security | str, quantity: float, limit_price: float) -> None: ...
    def stop_market_order(self, symbol: Symbol | Security | str, quantity: float, stop_price: float) -> None: ...
    def set_holdings(self, symbol: Symbol | Security | str, target: float) -> None:
        """Target a portfolio weight in [0, 1].  Computes and places the delta order."""
        ...
    def liquidate(self, symbol: Optional[Symbol | Security | str] = None) -> None:
        """Liquidate a position (or all positions when ``symbol`` is ``None``)."""
        ...

    # ── Algorithm Framework ───────────────────────────────────────────────────

    def add_alpha(self, model: AlphaModel) -> None:
        """Register an alpha model. Multiple calls compose models."""
        ...

    def set_portfolio_construction(self, model: PortfolioConstructionModel) -> None:
        """Set the portfolio construction model."""
        ...

    def set_execution(self, model: ExecutionModel) -> None:
        """Set the execution model."""
        ...

    def set_risk_management(self, model: RiskManagementModel) -> None:
        """Set the risk management model."""
        ...

    # ── Charting ──────────────────────────────────────────────────────────────

    def plot(self, chart: str, series: str, value: float) -> None: ...
    def add_chart(self, name: str) -> None: ...

    # ── Logging ───────────────────────────────────────────────────────────────

    def log(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...

    # ── Lifecycle hooks (override in subclass) ────────────────────────────────

    def initialize(self) -> None: ...
    def on_data(self, data: Slice) -> None: ...
    def on_order_event(self, event: OrderEvent) -> None: ...
    def on_end_of_algorithm(self) -> None: ...
    def on_warmup_finished(self) -> None: ...

# ── QuantBook ─────────────────────────────────────────────────────────────────

class QuantBook:
    """Research / notebook equivalent of QCAlgorithm.

    Usage (in a Jupyter notebook)::

        from AlgorithmImports import *

        qb = QuantBook()
        qb.set_start_date(2022, 1, 1)
        qb.set_end_date(2023, 1, 1)
        qb.set_data_folder("/data")

        spy = qb.add_equity("SPY")
        df = qb.history("SPY", 252, Resolution.Daily)
        # df is a dict: {"time": [...], "open": [...], ..., "close": [...]}
        # convert with pd.DataFrame(df)
    """

    def __init__(self) -> None: ...

    # ── Configuration ─────────────────────────────────────────────────────────

    def set_start_date(self, year: int, month: int, day: int) -> None: ...
    def set_end_date(self, year: int, month: int, day: int) -> None: ...
    def set_data_folder(self, path: str) -> None: ...
    def set_thetadata_provider(self, api_token: str) -> None: ...
    def set_polygon_provider(self, api_key: str) -> None: ...

    # ── Universe ──────────────────────────────────────────────────────────────

    def add_equity(self, ticker: str) -> Security: ...
    def add_option(self, ticker: str) -> Security: ...
    def add_future(self, ticker: str) -> Security: ...

    # ── History ───────────────────────────────────────────────────────────────

    def history(
        self,
        symbol: Symbol | str,
        bar_count: int,
        resolution: Resolution,
    ) -> Any:
        """Return the most recent ``bar_count`` bars as a column-oriented dict.

        The dict schema is::

            {
                "time":   List[str],   # ISO date strings
                "open":   List[float],
                "high":   List[float],
                "low":    List[float],
                "close":  List[float],
                "volume": List[float],
            }

        Pass the result directly to ``pd.DataFrame(qb.history(...))`` for a
        pandas-compatible DataFrame.
        """
        ...

    def history_range(
        self,
        symbol: Symbol | str,
        start: Tuple[int, int, int],
        end: Tuple[int, int, int],
        resolution: Resolution,
    ) -> Any:
        """Return bars for an explicit date range.  Same schema as ``history``."""
        ...

    # ── Indicators ────────────────────────────────────────────────────────────

    def indicator(
        self,
        name: str,
        symbol: Symbol | str,
        period: int,
        bar_count: int,
        resolution: Resolution,
    ) -> Any:
        """Compute a named indicator over historical bars.

        ``name`` is case-insensitive: ``"SMA"``, ``"EMA"``, ``"RSI"``,
        ``"MACD"``, ``"BB"`` / ``"BollingerBands"``, ``"ATR"``.

        Returns a dict with at least ``"time"`` and ``"value"`` keys.
        MACD also returns ``"signal"`` and ``"histogram"``.
        Bollinger Bands also returns ``"upper"`` and ``"lower"``.
        """
        ...

    # ── Options ───────────────────────────────────────────────────────────────

    def option_chain(self, ticker: str) -> List[Any]:
        """Return a list of option contract dicts for ``ticker``.

        Each dict has keys: ``symbol``, ``strike``, ``expiry``, ``right``,
        ``last_price``, ``bid``, ``ask``, ``volume``, ``open_interest``.
        Returns an empty list when no data is available.
        """
        ...

    # ── Prices ────────────────────────────────────────────────────────────────

    def get_last_price(self, symbol: Symbol | str) -> Optional[float]: ...
"#;

// ─── Entry point ──────────────────────────────────────────────────────────────

pub fn run_stubs(args: StubsArgs) -> Result<()> {
    match args.command {
        StubsCommand::Create { output } => run_create(output),
    }
}

fn run_create(output_override: Option<PathBuf>) -> Result<()> {
    let cwd = std::env::current_dir().context("Cannot determine current directory")?;

    let destinations: Vec<PathBuf> = if let Some(dir) = output_override {
        vec![dir.join("AlgorithmImports.pyi")]
    } else {
        let mut dests = vec![cwd.join("AlgorithmImports.pyi")];

        // Also install into Python site-packages when python3 is available.
        match site_packages_dir() {
            Ok(site) => dests.push(site.join("AlgorithmImports.pyi")),
            Err(e) => {
                eprintln!(
                    "warning: could not determine Python site-packages directory: {e}\n\
                     Stubs will only be written to the current directory."
                );
            }
        }

        dests
    };

    for dest in &destinations {
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("Cannot create directory '{}'", parent.display()))?;
        }
        std::fs::write(dest, STUB_CONTENT)
            .with_context(|| format!("Cannot write stubs to '{}'", dest.display()))?;
        println!("Stubs written: {}", dest.display());
    }

    // Scan ~/.rlean/plugins/ for installed plugins and note any stub files they provide.
    scan_plugin_stubs(&destinations)?;

    println!(
        "\nAlgorithmImports.pyi installed.  \
         Add the stub location to your IDE's `python.analysis.extraPaths` \
         (Pylance) or `stubPath` (Pyright) if it is not already on the path."
    );

    Ok(())
}

/// Query the active Python interpreter for the primary site-packages directory.
fn site_packages_dir() -> Result<PathBuf> {
    let out = SysCommand::new("python3")
        .args(["-c", "import site; print(site.getsitepackages()[0])"])
        .output()
        .context("Failed to run python3")?;

    if !out.status.success() {
        anyhow::bail!(
            "python3 exited with status {}: {}",
            out.status,
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }

    let path = String::from_utf8(out.stdout)
        .context("python3 output is not valid UTF-8")?
        .trim()
        .to_string();

    Ok(PathBuf::from(path))
}

/// Scan `~/.rlean/plugins/` for installed plugins and generate or copy any
/// stub files they expose.  Currently copies `*.pyi` files found at the
/// plugin root into each install destination directory.
fn scan_plugin_stubs(install_dirs: &[PathBuf]) -> Result<()> {
    let plugin_dir = dirs_home()?.join(".rlean").join("plugins");

    if !plugin_dir.exists() {
        return Ok(());
    }

    let read = std::fs::read_dir(&plugin_dir)
        .with_context(|| format!("Cannot read plugin directory '{}'", plugin_dir.display()))?;

    for entry in read.flatten() {
        let plugin_path = entry.path();
        if !plugin_path.is_dir() {
            continue;
        }

        // Look for *.pyi files the plugin provides alongside its binary.
        let Ok(files) = std::fs::read_dir(&plugin_path) else {
            continue;
        };
        for file in files.flatten() {
            let fp = file.path();
            if fp.extension().and_then(|e| e.to_str()) != Some("pyi") {
                continue;
            }
            let stub_name = fp.file_name().unwrap_or_default().to_os_string();
            let content = std::fs::read_to_string(&fp)
                .with_context(|| format!("Cannot read plugin stub '{}'", fp.display()))?;

            for dest_file in install_dirs {
                let dest_dir = dest_file.parent().unwrap_or(dest_file);
                let dest = dest_dir.join(&stub_name);
                std::fs::write(&dest, &content)
                    .with_context(|| format!("Cannot write plugin stub to '{}'", dest.display()))?;
                println!("Plugin stub written: {}", dest.display());
            }
        }
    }

    Ok(())
}

/// Return the user's home directory via `$HOME`.
fn dirs_home() -> Result<PathBuf> {
    if let Some(h) = std::env::var_os("HOME") {
        return Ok(PathBuf::from(h));
    }
    anyhow::bail!("Cannot determine home directory ($HOME is not set)")
}
