from __future__ import annotations

from datetime import date, datetime
from typing import Any, Optional

class QCAlgorithm:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_start_date(self, year: int, month: int, day: int) -> None: ...
    def set_end_date(self, year: int, month: int, day: int) -> None: ...
    def set_cash(self, amount: float) -> None: ...
    def add_cash(self, amount: float) -> None: ...
    def set_brokerage_model(self, brokerage: BrokerageName, account_type: AccountType) -> None: ...
    def set_benchmark(self, ticker: str) -> None: ...
    def get_parameter(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
    def set_parameter(self, key: str, value: str) -> None: ...
    def has_security(self, symbol: Symbol) -> bool: ...
    def history(self, symbol: Symbol, periods: int, resolution: Resolution) -> dict[str, list[str]]: ...
    def add_equity(self, ticker: str, resolution: Resolution, leverage: Optional[float] = None) -> Security: ...
    def add_option(self, underlying_ticker: str, resolution: Resolution) -> Option: ...
    def add_data(self, source_type: str, ticker: str, resolution: Resolution, properties: Optional[dict[str, str]] = None) -> Security: ...
    def set_warm_up(self, n: int, resolution: Optional[Resolution] = None) -> None: ...
    def market_order(self, symbol: Symbol, quantity: float, time_in_force: Optional[TimeInForce] = None, outside_regular_trading_hours: Optional[bool] = None) -> OrderTicket: ...
    def limit_order(self, symbol: Symbol, quantity: float, limit_price: float, time_in_force: Optional[TimeInForce] = None, outside_regular_trading_hours: bool = False, post_only: bool = False) -> OrderTicket: ...
    def stop_market_order(self, symbol: Symbol, quantity: float, stop_price: float, time_in_force: Optional[TimeInForce] = None, outside_regular_trading_hours: bool = False) -> OrderTicket: ...
    def sma(self, symbol: Symbol, period: int, resolution: Resolution) -> SimpleMovingAverage: ...
    def ema(self, symbol: Symbol, period: int, resolution: Resolution) -> ExponentialMovingAverage: ...
    def rsi(self, symbol: Symbol, period: int, moving_average_type: MovingAverageType, resolution: Resolution) -> RelativeStrengthIndex: ...
    def momp(self, symbol: Symbol, period: int, resolution: Resolution) -> MomentumPercent: ...
    def std(self, symbol: Symbol, period: int, resolution: Resolution) -> StandardDeviation: ...
    def bb(self, symbol: Symbol, period: int, k: float, moving_average_type: MovingAverageType, resolution: Resolution) -> BollingerBands: ...
    def macd(self, symbol: Symbol, fast_period: int, slow_period: int, signal_period: int, moving_average_type: MovingAverageType, resolution: Resolution) -> MovingAverageConvergenceDivergence: ...
    def identity(self, symbol: Symbol, resolution: Resolution) -> Identity: ...
    def register_indicator(self, symbol: Symbol, indicator: Identity, resolution: Optional[Resolution] = None) -> None: ...
    def warm_up_indicator(self, symbol: Symbol, indicator: Identity, resolution: Optional[Resolution] = None) -> None: ...
    def add_alpha(self, model: AlphaModel) -> None: ...
    def set_portfolio_construction(self, model: PortfolioConstructionModel) -> None: ...
    def set_execution(self, model: ExecutionModel) -> None: ...
    def set_risk_management(self, model: RiskManagementModel) -> None: ...
    def add_universe(self, source_type: str, ticker: str, resolution: Resolution, selector: Any) -> None: ...
    def set_custom_data_symbols(self, source_type: str, ticker: str, symbols: list[str]) -> None: ...
    @property
    def cash(self) -> float: ...
    @property
    def portfolio_value(self) -> float: ...
    @property
    def portfolio(self) -> Portfolio: ...
    @property
    def insights(self) -> InsightCollection: ...
    @property
    def securities(self) -> SecurityManager: ...
    @property
    def time(self) -> datetime: ...
    @property
    def universe_settings(self) -> UniverseSettings: ...
    @property
    def settings(self) -> AlgorithmSettings: ...

class QuantBook: ...
class Symbol:
    @staticmethod
    def create(ticker: str, security_type: Optional[SecurityType] = None, market: Optional[str] = None) -> Symbol: ...
    @staticmethod
    def create_equity(ticker: str, market: Optional[str] = None) -> Symbol: ...
    @staticmethod
    def create_index(ticker: str, market: Optional[str] = None) -> Symbol: ...
    @property
    def value(self) -> str: ...
    @property
    def ticker(self) -> str: ...
    @property
    def sid(self) -> int: ...

class Resolution:
    Tick: Resolution
    TICK: Resolution
    Second: Resolution
    SECOND: Resolution
    Minute: Resolution
    MINUTE: Resolution
    Hour: Resolution
    HOUR: Resolution
    Daily: Resolution
    DAILY: Resolution

class SecurityType:
    Equity: SecurityType
    EQUITY: SecurityType
    Option: SecurityType
    OPTION: SecurityType
    Index: SecurityType
    INDEX: SecurityType
    Crypto: SecurityType
    CRYPTO: SecurityType

class OptionRight:
    Call: OptionRight
    CALL: OptionRight
    Put: OptionRight
    PUT: OptionRight

class OptionStyle:
    American: OptionStyle
    AMERICAN: OptionStyle
    European: OptionStyle
    EUROPEAN: OptionStyle

class TimeInForce:
    GoodTilCanceled: TimeInForce
    GOOD_TIL_CANCELED: TimeInForce
    Day: TimeInForce
    DAY: TimeInForce
    ImmediateOrCancel: TimeInForce
    IMMEDIATE_OR_CANCEL: TimeInForce
    FillOrKill: TimeInForce
    FILL_OR_KILL: TimeInForce

class OrderStatus: ...
class OrderType: ...
class OrderDirection: ...
class DataNormalizationMode: ...
class AccountType: ...
class BrokerageName: ...
class MovingAverageType: ...
class Market: ...
class HyperliquidUniverse: ...

class UniverseSettings: ...
class DateRule: ...
class DateRules: ...
class TimeRule: ...
class TimeRules: ...
class ScheduledUniverse: ...
class SecurityChanges: ...

class Security:
    @property
    def symbol(self) -> Symbol: ...
    @property
    def price(self) -> float: ...
    @property
    def exchange(self) -> SecurityExchange: ...

class Option:
    @property
    def symbol(self) -> Symbol: ...
    def set_filter(self, min_strike_rank: int, max_strike_rank: int, min_expiry_days: int, max_expiry_days: int) -> None: ...

class SecurityExchange:
    @property
    def hours(self) -> SecurityExchangeHours: ...

class SecurityExchangeHours:
    def is_open(self, start: datetime, end: Optional[datetime] = None, extended: Optional[bool] = None) -> bool: ...

class SecurityManager:
    def __getitem__(self, symbol: Symbol) -> Security: ...
    def contains_key(self, symbol: Symbol) -> bool: ...

class AlgorithmSettings:
    def get(self, name: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...

class Slice: ...
class OptionChains: ...
class TradeBars: ...
class TradeBar: ...
class Bar: ...
class QuoteBars: ...
class QuoteBar: ...
class Ticks: ...
class Tick: ...
class CustomData: ...
class CustomDataPoint: ...

class OrderTicket: ...
class OrderEvent: ...
class SecurityHolding: ...
class Portfolio: ...
class ChartCollection: ...
class InsightCollection: ...

class Greeks: ...
class OptionUnderlying: ...
class OptionContract: ...
class OptionChain: ...

class IndicatorDataPoint: ...
class IndicatorResult: ...
class SimpleMovingAverage: ...
class ExponentialMovingAverage: ...
class RelativeStrengthIndex: ...
class MomentumPercent: ...
class StandardDeviation: ...
class BollingerBands: ...
class MovingAverageConvergenceDivergence: ...
class AverageTrueRange: ...
class Identity: ...

class InsightDirection: ...
class PortfolioBias: ...
class AlphaModel: ...
class ExecutionModel: ...
class PortfolioConstructionModel: ...
class RiskManagementModel: ...
class InsightWeightingPortfolioConstructionModel: ...
class EqualWeightingPortfolioConstructionModel: ...
class MeanVarianceOptimizationPortfolioConstructionModel: ...
class MaximumSharpeRatioPortfolioConstructionModel: ...
class ImmediateExecutionModel: ...
class NullExecutionModel: ...
class VWAPExecutionModel: ...
class StandardDeviationExecutionModel: ...
class NullRiskManagementModel: ...
class MaximumDrawdownPercentPerSecurity: ...
class TrailingStopRiskManagementModel: ...
class ConstantAlphaModel: ...
class EmaCrossAlphaModel: ...
class HistoricalReturnsAlphaModel: ...
class MacdAlphaModel: ...
class RsiAlphaModel: ...
class Insight: ...
class PortfolioTarget: ...
