[package]
name = "lean-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
lean-core = { path = "../lean-core" }
lean-data = { path = "../lean-data" }
lean-algorithm = { path = "../lean-algorithm" }
lean-orders = { path = "../lean-orders" }
lean-options = { path = "../lean-options" }
lean-alpha = { path = "../lean-alpha" }
lean-execution = { path = "../lean-execution" }
lean-portfolio-construction = { path = "../lean-portfolio-construction" }
lean-risk = { path = "../lean-risk" }
lean-indicators = { path = "../lean-indicators" }
lean-sdk-annotations = { path = "../lean-sdk-annotations" }

anyhow = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
