[package]
name = "lean-universe"
version.workspace = true
edition.workspace = true
description = "Universe selection framework for rlean."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
lean-core = { path = "../lean-core", version = "0.1.1" }
lean-data = { path = "../lean-data", version = "0.1.1" }
serde = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
