[package]
name = "lean-plugin"
version.workspace = true
edition.workspace = true
description = "Plugin ABI for rlean — defines the C-stable interface every rlean plugin must export"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
rustls      = { workspace = true }
